# Generated by Django 3.0.5 on 2020-05-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('grade', models.IntegerField()),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('personal_photo', models.ImageField(blank=True, upload_to='personal_photo')),
                ('student_card_front', models.ImageField(blank=True, upload_to='student_card_front')),
                ('student_card_back', models.ImageField(blank=True, upload_to='student_card_back')),
                ('ID_card', models.ImageField(blank=True, upload_to='ID_card')),
                ('proof', models.ImageField(blank=True, upload_to='proof')),
            ],
        ),
        migrations.CreateModel(
            name='Playing_Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('sport_name', models.CharField(choices=[('gb', 'girls_basketball'), ('bb', 'boys_basketball'), ('gv', 'girls_volleyball'), ('bv', 'boys_volleyball'), ('bm', 'badminton'), ('sw', 'swimming'), ('ba', 'baseball')], max_length=15)),
                ('points_left', models.IntegerField()),
                ('points_received', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(choices=[('gb', 'girls_basketball'), ('bb', 'boys_basketball'), ('gv', 'girls_volleyball'), ('bv', 'boys_volleyball'), ('bm', 'badminton'), ('sw', 'swimming'), ('ba', 'baseball')], max_length=10)),
                ('captain_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('court', models.CharField(max_length=20)),
            ],
        ),
    ]
