# Generated by Django 3.0.5 on 2020-06-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(null=True)),
                ('expire_time', models.DateTimeField(null=True)),
                ('sport_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Noticing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateTimeField(null=True)),
                ('paragraph', models.TextField()),
                ('sport_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Team')),
            ],
        ),
    ]
