# Generated by Django 3.0.5 on 2020-05-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playing_sport',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain_id',
        ),
        migrations.AddField(
            model_name='playing_sport',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Player'),
        ),
        migrations.AddField(
            model_name='training',
            name='sport_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Team'),
        ),
        migrations.AlterField(
            model_name='playing_sport',
            name='sport_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Team'),
        ),
    ]
