# Generated by Django 3.0.5 on 2020-06-04 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200603_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticing',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='participant',
            field=models.ManyToManyField(to='catalog.Playing_Sport'),
        ),
        migrations.AddField(
            model_name='training',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voting',
            name='participant',
            field=models.ManyToManyField(to='catalog.Playing_Sport'),
        ),
        migrations.AddField(
            model_name='voting',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
