# Generated by Django 3.0.5 on 2020-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200515_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport_name',
            field=models.CharField(choices=[('女籃', 'girls_basketball'), ('男籃', 'boys_basketball'), ('女排', 'girls_volleyball'), ('男排', 'boys_volleyball'), ('羽球', 'badminton'), ('游泳', 'swimming'), ('棒壘', 'baseball')], max_length=10),
        ),
    ]
