# Generated by Django 3.0.5 on 2020-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200515_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default=123456, max_length=256),
            preserve_default=False,
        ),
    ]
