# Generated by Django 3.0.5 on 2020-06-05 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200605_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 15, 57, 48, 351971)),
        ),
        migrations.AddField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 15, 57, 48, 349009)),
        ),
        migrations.AddField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 15, 57, 48, 350001)),
        ),
    ]
