# Generated by Django 3.0.5 on 2020-06-05 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200605_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 1, 33, 40, 275914)),
        ),
        migrations.AlterField(
            model_name='player',
            name='ID_card',
            field=models.ImageField(blank=True, upload_to='images/ID_card'),
        ),
        migrations.AlterField(
            model_name='player',
            name='personal_photo',
            field=models.ImageField(blank=True, upload_to='images/personal_photo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='proof',
            field=models.ImageField(blank=True, upload_to='images/proof'),
        ),
        migrations.AlterField(
            model_name='player',
            name='student_card_back',
            field=models.ImageField(blank=True, upload_to='images/student_card_back'),
        ),
        migrations.AlterField(
            model_name='player',
            name='student_card_front',
            field=models.ImageField(blank=True, upload_to='images/student_card_front'),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 1, 33, 40, 270928)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 1, 33, 40, 273921)),
        ),
    ]
