# Generated by Django 3.0.5 on 2020-06-05 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200606_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 31, 12, 630759)),
        ),
        migrations.AlterField(
            model_name='player',
            name='personal_photo',
            field=models.ImageField(default='images/personal_photo/unknown_user.jpg', upload_to='images/personal_photo'),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 31, 12, 626769)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 31, 12, 628764)),
        ),
    ]
