# Generated by Django 3.0.5 on 2020-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200518_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
