# Generated by Django 3.0.5 on 2020-06-05 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200606_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 48, 41, 219746)),
        ),
        migrations.AlterField(
            model_name='playing_sport',
            name='points_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 48, 41, 215757)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 48, 41, 217751)),
        ),
    ]
