# Generated by Django 3.0.5 on 2020-06-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200607_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 4, 18, 163113)),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 4, 18, 159121)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 4, 18, 161116)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option_three',
            field=models.TextField(null=True),
        ),
    ]
