# Generated by Django 3.0.5 on 2020-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='郭又嘉', max_length=20),
            preserve_default=False,
        ),
    ]
