# Generated by Django 3.0.5 on 2020-05-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playing_sport',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playing_sport',
            name='sport_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='training',
            name='sport_name',
        ),
    ]
