# Generated by Django 3.0.5 on 2020-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200519_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
