# Generated by Django 3.0.5 on 2020-06-07 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200607_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 18, 46, 625659)),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 18, 46, 622639)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 18, 46, 624659)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='expire_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
