# Generated by Django 3.0.5 on 2020-06-09 23:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200608_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availible_Day_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='noticing',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 7, 42, 36, 11570)),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 7, 42, 36, 595)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 7, 42, 36, 1566)),
        ),
        migrations.CreateModel(
            name='Availible_Day_Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(default=0)),
                ('tuesday', models.IntegerField(default=0)),
                ('wednesday', models.IntegerField(default=0)),
                ('thursday', models.IntegerField(default=0)),
                ('friday', models.IntegerField(default=0)),
                ('participant', models.ManyToManyField(blank=True, to='catalog.Availible_Day_Player')),
                ('sport_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Team')),
            ],
        ),
        migrations.AddField(
            model_name='availible_day_player',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
